title: Gina Ferguson QA Engineer
description: >-
  Gina Ferguson is a QA Engineer with over 6.5 years of tech experience, 
  and a currently undergrad for Computer Science.
baseurl: "ginaferguson.net"
url: "https://ginaferguson.net"
theme: jekyll-theme-hacker
